# Site
name: 'നിഴലുകള്‍ പറഞ്ഞത് ...'
title: "നിഴലുകള്‍ പറഞ്ഞത് ..."
description: 'ഗിനി ഗംഗാധരന്‍'
logo: 'assets/images/logo-g-v1.png'
favicon: 'assets/images/logo-g-v1.png'

#url: "https://www.iamgini.com/"
my_base_site: "https://www.iamgini.com"
baseurl: ''
# If you are building a GitHub project page then use these settings:
# url: "https://www.iamgini.com/site2/"
# baseurl: "/site2"

disqus: 'iamgini-com'
email: 'net.gini@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

google_analytics: 'UA-158250524-1'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
  gini:
    name: Gini
    display_name: Gini Gangadharan 
    site: https://www.iamgini.com
    avatar: 'assets/images/avatar.png'
    gravatar: 1558aaf0c06196e6b9cb24c21e5ca858
    email: net.gini@gmail.com
    bio: "Backpacker, Foodie, Techie"
    web: https://www.iamgini.com
    twitter: https://twitter.com/ginigangadharan
    description: "Backpacker, Foodie, Techie"
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
